version: '3'
services:
  db: 
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Tapatapita123
      - MYSQL_DATABASE=db_MassiveGaming
  web:
    build: MassiveGaming/.
    expose: 
      - "8443"
    restart: unless-stopped
    environment:
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/db_MassiveGaming
    deploy:
      mode: loadbalancer
      replicas: 2
  broker:
    image: rabbitmq
  internalservice:
    build: InternalService/.
    environment:
      - SPRING_RABBITMQ_HOST=broker
    deploy:
      mode: replicated
      replicas: 2
  loadbalancer:
    image: haproxy:2.7.3
    ports:
      - "9443:443" # Only service that is exposed to the host is the lb
      - "8181:8181" # Haproxy Stats
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    restart: unless-stopped